
let suggestions = [
    'Alibaba',
    'Alvin and the chipmunks',
    'Avengers',
    'Bad',
    'Banner',
    'Channel',
    'Coding',
    'Coder',
    'Hacker',
    'Programmer',
    'YouTube',
    'YouTube Channel',
    'Blogger',
    'BollyWood',
    'Vlogger',
    'Vehicles',
    'Facebook',
    'Facebook.com',
    'Freelancer',
    'Facebook Page',
    'Designer',
    'UI/UX Designer',
    'Developer',
    'Web Designer',
    'Facebook.com',
    'Freelancer',
    'Facebook Page',
    'Designer',
    'UI/UX Designer',
    'Developer',
    'Web Designer',
    'Web Development',
    'Web Developer',
    'Login form in html & css',
    'How to learn html & css',
    'How to learn Javascript',
    'How to become a freelancer',
    'How to become Web Developer',
    'How to start a YouTube Channel',
    'What does  HTML stands for?',
    'What does CSS stands for?'
]